Fix of `NoClassDefFoundError` due to unintended Lincheck analysis of `StackTraceElement` methods (#423)
---------

Signed-off-by: Evgeniy Moiseenko <evg.moiseenko94@gmail.com>